#!/usr/local/bin/zsh
current=`cd $(dirname $0) && pwd`

expect -c "
set timeout -1
stty -echo
send_user \"Password:\"
expect_user -re \"(.*)\n\"
send_user \"\n\"
set PW \$expect_out(1,string)
stty echo
spawn ${current}/brew-update-commands
expect \"Password:\"
send \$PW
send \"\n\"
interact
"
