#!/usr/local/bin/zsh

echo ''
echo 'brew update & upgrade...'
brew update && brew upgrade && echo '...finished.'

sudo chown -R $(whoami):staff /usr/local/Caskroom/

for cask in $( brew cask list ); do
	echo "App: "${cask}
	info=`brew cask info ${cask}`
	version=`echo ${info} | fgrep "${cask}: " | sed "s/${cask}: //"`
	if [ ${version} = "latest" ]; then
		echo "latest version (force update)."
		brew cask install ${cask} --force
	elif [[ $(echo ${info} | fgrep "/usr/local" | fgrep "${version}") ]]; then
		echo "latest version (not update)."
	else
		echo "old version (update)."
		brew cask install ${cask} --force
		if [ ${cask} = "karabiner" ]; then
			open /Applications/Karabiner.app
		fi
	fi
done

echo "Remove old verions of cask."
for cask in /usr/local/Caskroom/*; do
	vl=(`ls -t ${cask}`) && for version in "${vl[@]:1}"; do
		rm -rf "${cask}/${version}";
	done
done

#clean up
brew cask cleanup
brew cleanup

echo "Rebuilding the Spotlight index."
sudo mdutil -E /
